repositories:
  remote:
   - https://repo.maven.apache.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/staging

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.14

  # GWT deps
  gwt_user: org.realityforge.com.google.gwt:gwt-user:jar:2.8.2-v20191108
  gwt_dev: org.realityforge.com.google.gwt:gwt-dev:jar:2.8.2-v20191108

  shade_task: org.realityforge.ant.shade:ant-shade-task:jar:0.1

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1

  proton_core: org.realityforge.proton:proton-core:jar:0.32
  proton_qa: org.realityforge.proton:proton-qa:jar:0.32

  compile_testing: com.google.testing.compile:compile-testing:jar:0.18-rf
  truth: com.google.truth:truth:jar:0.45
  junit: junit:junit:jar:4.12
  hamcrest_core: org.hamcrest:hamcrest-core:jar:1.3
  guava: com.google.guava:guava:jar:27.1-jre
  guava_failureaccess: com.google.guava:failureaccess:jar:1.0.1

  javax_json: org.glassfish:javax.json:jar:1.1
