repositories:
  remote:
   - https://stocksoftware.jfrog.io/stocksoftware/maven2
   - https://repo.maven.apache.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/staging

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.17

  # GWT deps
  gwt_user: com.google.gwt:gwt-user:jar:2.9.0
  gwt_dev: com.google.gwt:gwt-dev:jar:2.9.0

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1

  proton_core: org.realityforge.proton:proton-core:jar:0.57
  proton_qa: org.realityforge.proton:proton-qa:jar:0.57

  javax_json: org.glassfish:javax.json:jar:1.1
